<a href="https://colab.research.google.com/github/bragind/MIFI/blob/main/pandas_students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
countries_data = pd.read_csv('data/countries.csv', sep=';')
display(countries_data)

FileNotFoundError: [Errno 2] No such file or directory: 'data/countries.csv'

In [7]:
import pandas as pd

In [13]:
student_data = pd.read_csv('/students_performance.csv', sep = ',')
student_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [14]:
student_data.loc[155]

gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                               70
reading score                            89
writing score                            88
Name: 155, dtype: object

In [16]:
student_data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [21]:
#Каков у студентов средний балл по математике?
#Округлите ответ до целого числа.

print(student_data['math score'].mean())

66.089

In [23]:
'''
Какая расовая группа является самой крупной в учебном заведении?
В качестве ответа введите идентификатор группы (A, B, C, D, F).
'''
student_data.groupby('race/ethnicity').count()

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
race/ethnicity,,,,,,,
group A,89,89,89,89,89,89,89
group B,190,190,190,190,190,190,190
group C,319,319,319,319,319,319,319
group D,262,262,262,262,262,262,262
group E,140,140,140,140,140,140,140

In [24]:
#Каков средний балл по чтению у студентов, которые посещали курсы подготовки к экзаменам?
# Фильтрация строк, где test preparation course == 'completed'
filtered_df = student_data.query("`test preparation course` == 'completed'")

# Вычисление среднего балла по чтению
average_reading_score = filtered_df['reading score'].mean()
average_reading_score

73.89385474860335

In [25]:
#Сколько студентов получили 0 баллов по математике?
# Фильтруем строки, где math score равен 0
zero_math_scores = student_data.query("`math score` == 0")

# Количество таких строк
number_of_zero_math_scores = len(zero_math_scores)

print(number_of_zero_math_scores)

1

In [26]:
'''Проверьте гипотезу: у студентов с оплачиваемым питанием средний балл по математике выше, чем у студентов с льготным питанием.
В качестве ответа напишите наибольший средний балл по математике среди этих групп студентов.
Округлите ответ до целого числа.'''
# Группы студентов по типу питания
paid_lunch_students = student_data.query("`lunch` == 'standard'")
reduced_lunch_students = student_data.query("`lunch` != 'standard'")

# Средние баллы по математике для каждой группы
avg_paid_math_score = paid_lunch_students['math score'].mean()
avg_reduced_math_score = reduced_lunch_students['math score'].mean()

# Наибольший средний балл по математике среди двух групп
max_avg_math_score = max(avg_paid_math_score, avg_reduced_math_score)

# Округляем до целого числа
rounded_max_avg_math_score = round(max_avg_math_score)

print(rounded_max_avg_math_score)

70

In [40]:
'''Каков процент студентов, родители которых имеют высшее образование уровня бакалавриата (bachelor's degree)?
Округлите ответ до целого числа.'''
student_data["parental level of education"].value_counts(normalize=True)

parental level of education
some college          0.226
associate's degree    0.222
high school           0.196
some high school      0.179
bachelor's degree     0.118
master's degree       0.059
Name: proportion, dtype: float64

In [39]:
#Насколько медианный балл по письму у студентов в расовой группе А отличается от среднего балла по письму у студентов в расовой группе C?
# Группа А
group_A = student_data.query("`race/ethnicity` == 'group A'")
median_writing_group_A = group_A['writing score'].median()

# Группа C
group_C = student_data.query("`race/ethnicity` == 'group C'")
mean_writing_group_C = group_C['writing score'].mean()

# Абсолютная разница между медианой группы А и средним группы C
difference = abs(median_writing_group_A - mean_writing_group_C)

# Округление разницы до целого числа
rounded_difference = round(difference)

print(rounded_difference)

6